platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5-jdk-8

inputs:
- name: git-repo

outputs:
- name: target
  path: ./git-repo/target

run:
  path: ./git-repo/ci/build.sh