resource_types:
  - name: maven-cache
    type: docker-image
    source:
      repository: olhtbr/maven-cache-resource
      tag: latest

jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: package
    privileged: true
    file: git-repo/ci/build.yml

