resource_types:
  - name: maven-cache
    type: docker-image
    source:
      repository: olhtbr/maven-cache-resource
      tag: latest

resources:
- name: git-repo
  type: git
  source: &git-repo
    uri: https://github.com/nwoike/spring-music.git
    branch: ci
- name: maven-cache
  type: maven-cache
  source:
    <<: *git-repo
    paths:
      - pom.xml

jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - get: maven-cache
  - task: package
    privileged: true
    file: git-repo/ci/build.yml

